# Generated by Django 5.1.7 on 2025-05-09 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gqlauth", "0004_captcha"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Captcha",
        ),
    ]
